name: Publish

on:
  push:
    tags:
      - 'v*'  # Triggers on tags starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          poetry install
      - name: Configure Poetry for PyPI
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish package to PyPI
        run: |
          poetry publish --repository pypi --build
      - name: Check for Successful Publication
        run: |
          version=$(poetry version --short)
          echo "Checking if package execexam version $version is available on PyPI..."
          response=$(curl -s "https://pypi.org/pypi/execexam/$version/json")
          if echo "$response" | grep -q "$version"; then
            echo "Package execexam version $version is successfully published on PyPI."
          else
            echo "Package execexam version $version was not found on PyPI."
            exit 1
          fi
